export const TR_CITIES = [
   { name: 'Adana', plateCode: '01' },
   { name: 'Adıyaman', plateCode: '02' },
   { name: 'Afyonkarahisar', plateCode: '03' },
   { name: 'Ağrı', plateCode: '04' },
   { name: 'Amasya', plateCode: '05' },
   { name: 'Ankara', plateCode: '06' },
   { name: 'Antalya', plateCode: '07' },
   { name: 'Artvin', plateCode: '08' },
   { name: 'Aydın', plateCode: '09' },
   { name: 'Balıkesir', plateCode: '10' },
   { name: 'Bilecik', plateCode: '11' },
   { name: 'Bingöl', plateCode: '12' },
   { name: 'Bitlis', plateCode: '13' },
   { name: 'Bolu', plateCode: '14' },
   { name: 'Burdur', plateCode: '15' },
   { name: 'Bursa', plateCode: '16' },
   { name: 'Çanakkale', plateCode: '17' },
   { name: 'Çankırı', plateCode: '18' },
   { name: 'Çorum', plateCode: '19' },
   { name: 'Denizli', plateCode: '20' },
   { name: 'Diyarbakır', plateCode: '21' },
   { name: 'Edirne', plateCode: '22' },
   { name: 'Elazığ', plateCode: '23' },
   { name: 'Erzincan', plateCode: '24' },
   { name: 'Erzurum', plateCode: '25' },
   { name: 'Eskişehir', plateCode: '26' },
   { name: 'Gaziantep', plateCode: '27' },
   { name: 'Giresun', plateCode: '28' },
   { name: 'Gümüşhane', plateCode: '29' },
   { name: 'Hakkari', plateCode: '30' },
   { name: 'Hatay', plateCode: '31' },
   { name: 'Isparta', plateCode: '32' },
   { name: 'Mersin', plateCode: '33' },
   { name: 'İstanbul', plateCode: '34' },
   { name: 'İzmir', plateCode: '35' },
   { name: 'Kars', plateCode: '36' },
   { name: 'Kastamonu', plateCode: '37' },
   { name: 'Kayseri', plateCode: '38' },
   { name: 'Kırklareli', plateCode: '39' },
   { name: 'Kırşehir', plateCode: '40' },
   { name: 'Kocaeli', plateCode: '41' },
   { name: 'Konya', plateCode: '42' },
   { name: 'Kütahya', plateCode: '43' },
   { name: 'Malatya', plateCode: '44' },
   { name: 'Manisa', plateCode: '45' },
   { name: 'Kahramanmaraş', plateCode: '46' },
   { name: 'Mardin', plateCode: '47' },
   { name: 'Muğla', plateCode: '48' },
   { name: 'Muş', plateCode: '49' },
   { name: 'Nevşehir', plateCode: '50' },
   { name: 'Niğde', plateCode: '51' },
   { name: 'Ordu', plateCode: '52' },
   { name: 'Rize', plateCode: '53' },
   { name: 'Sakarya', plateCode: '54' },
   { name: 'Samsun', plateCode: '55' },
   { name: 'Siirt', plateCode: '56' },
   { name: 'Sinop', plateCode: '57' },
   { name: 'Sivas', plateCode: '58' },
   { name: 'Tekirdağ', plateCode: '59' },
   { name: 'Tokat', plateCode: '60' },
   { name: 'Trabzon', plateCode: '61' },
   { name: 'Tunceli', plateCode: '62' },
   { name: 'Şanlıurfa', plateCode: '63' },
   { name: 'Uşak', plateCode: '64' },
   { name: 'Van', plateCode: '65' },
   { name: 'Yozgat', plateCode: '66' },
   { name: 'Zonguldak', plateCode: '67' },
   { name: 'Aksaray', plateCode: '68' },
   { name: 'Bayburt', plateCode: '69' },
   { name: 'Karaman', plateCode: '70' },
   { name: 'Kırıkkale', plateCode: '71' },
   { name: 'Batman', plateCode: '72' },
   { name: 'Şırnak', plateCode: '73' },
   { name: 'Bartın', plateCode: '74' },
   { name: 'Ardahan', plateCode: '75' },
   { name: 'Iğdır', plateCode: '76' },
   { name: 'Yalova', plateCode: '77' },
   { name: 'Karabük', plateCode: '78' },
   { name: 'Kilis', plateCode: '79' },
   { name: 'Osmaniye', plateCode: '80' },
   { name: 'Düzce', plateCode: '81' },
]

export const TR_DISTRICTS: Record<string, string[]> = {
   'Adana': ['Aladağ', 'Ceyhan', 'Çukurova', 'Feke', 'İmamoğlu', 'Karaisalı', 'Karataş', 'Kozan', 'Pozantı', 'Saimbeyli', 'Sarıçam', 'Seyhan', 'Tufanbeyli', 'Yumurtalık', 'Yüreğir'],
   'Adıyaman': ['Besni', 'Çelikhan', 'Gerger', 'Gölbaşı', 'Kahta', 'Merkez', 'Samsat', 'Sincik', 'Tut'],
   'Afyonkarahisar': ['Başmakçı', 'Bayat', 'Bolvadin', 'Çay', 'Çobanlar', 'Dazkırı', 'Dinar', 'Emirdağ', 'Evciler', 'Hocalar', 'İhsaniye', 'İscehisar', 'Kızılören', 'Merkez', 'Sandıklı', 'Sinanpaşa', 'Sultandağı', 'Şuhut'],
   'Ağrı': ['Diyadin', 'Doğubayazıt', 'Eleşkirt', 'Hamur', 'Merkez', 'Patnos', 'Taşlıçay', 'Tutak'],
   'Amasya': ['Göynücek', 'Gümüşhacıköy', 'Hamamözü', 'Merkez', 'Merzifon', 'Suluova', 'Taşova'],
   'Ankara': ['Akyurt', 'Altındağ', 'Ayaş', 'Bala', 'Beypazarı', 'Çamlıdere', 'Çankaya', 'Çubuk', 'Elmadağ', 'Etimesgut', 'Evren', 'Gölbaşı', 'Güdül', 'Haymana', 'Kahramankazan', 'Kalecik', 'Keçiören', 'Kızılcahamam', 'Mamak', 'Nallıhan', 'Polatlı', 'Pursaklar', 'Sincan', 'Şereflikoçhisar', 'Yenimahalle'],
   'Antalya': ['Akseki', 'Aksu', 'Alanya', 'Demre', 'Döşemealtı', 'Elmalı', 'Finike', 'Gazipaşa', 'Gündoğmuş', 'İbradı', 'Kaş', 'Kemer', 'Kepez', 'Konyaaltı', 'Korkuteli', 'Kumluca', 'Manavgat', 'Muratpaşa', 'Serik'],
   'Artvin': ['Ardanuç', 'Arhavi', 'Borçka', 'Hopa', 'Merkez', 'Murgul', 'Şavşat', 'Yusufeli'],
   'Aydın': ['Bozdoğan', 'Buharkent', 'Çine', 'Didim', 'Efeler', 'Germencik', 'İncirliova', 'Karacasu', 'Karpuzlu', 'Koçarlı', 'Köşk', 'Kuşadası', 'Kuyucak', 'Nazilli', 'Söke', 'Sultanhisar', 'Yenipazar'],
   'Balıkesir': ['Altıeylül', 'Ayvalık', 'Balya', 'Bandırma', 'Bigadiç', 'Burhaniye', 'Dursunbey', 'Edremit', 'Erdek', 'Gömeç', 'Gönen', 'Havran', 'İvrindi', 'Karesi', 'Kepsut', 'Manyas', 'Marmara', 'Savaştepe', 'Sındırgı', 'Susurluk'],
   'Bilecik': ['Bozüyük', 'Gölpazarı', 'İnhisar', 'Merkez', 'Osmaneli', 'Pazaryeri', 'Söğüt', 'Yenipazar'],
   'Bingöl': ['Adaklı', 'Genç', 'Karlıova', 'Kiğı', 'Merkez', 'Solhan', 'Yayladere', 'Yedisu'],
   'Bitlis': ['Adilcevaz', 'Ahlat', 'Güroymak', 'Hizan', 'Merkez', 'Mutki', 'Tatvan'],
   'Bolu': ['Dörtdivan', 'Gerede', 'Göynük', 'Kıbrıscık', 'Mengen', 'Merkez', 'Mudurnu', 'Seben', 'Yeniçağa'],
   'Burdur': ['Ağlasun', 'Altınyayla', 'Bucak', 'Çavdır', 'Çeltikçi', 'Gölhisar', 'Karamanlı', 'Kemer', 'Merkez', 'Tefenni', 'Yeşilova'],
   'Bursa': ['Büyükorhan', 'Gemlik', 'Gürsu', 'Harmancık', 'İnegöl', 'İznik', 'Karacabey', 'Keles', 'Kestel', 'Mudanya', 'Mustafakemalpaşa', 'Nilüfer', 'Orhaneli', 'Orhangazi', 'Osmangazi', 'Yenişehir', 'Yıldırım'],
   'Çanakkale': ['Ayvacık', 'Bayramiç', 'Biga', 'Bozcaada', 'Çan', 'Eceabat', 'Ezine', 'Gelibolu', 'Gökçeada', 'Lapseki', 'Merkez', 'Yenice'],
   'Çankırı': ['Atkaracalar', 'Bayramören', 'Çerkeş', 'Eldivan', 'Ilgaz', 'Kızılırmak', 'Korgun', 'Kurşunlu', 'Merkez', 'Orta', 'Şabanözü', 'Yapraklı'],
   'Çorum': ['Alaca', 'Bayat', 'Boğazkale', 'Dodurga', 'İskilip', 'Kargı', 'Laçin', 'Mecitözü', 'Merkez', 'Oğuzlar', 'Ortaköy', 'Osmancık', 'Sungurlu', 'Uğurludağ'],
   'Denizli': ['Acıpayam', 'Babadağ', 'Baklan', 'Bekilli', 'Beyağaç', 'Bozkurt', 'Buldan', 'Çal', 'Çameli', 'Çardak', 'Çivril', 'Güney', 'Honaz', 'Kale', 'Merkezefendi', 'Pamukkale', 'Sarayköy', 'Serinhisar', 'Tavas'],
   'Diyarbakır': ['Bağlar', 'Bismil', 'Çermik', 'Çınar', 'Çüngüş', 'Dicle', 'Eğil', 'Ergani', 'Hani', 'Hazro', 'Kayapınar', 'Kocaköy', 'Kulp', 'Lice', 'Silvan', 'Sur', 'Yenişehir'],
   'Edirne': ['Enez', 'Havsa', 'İpsala', 'Keşan', 'Lalapaşa', 'Meriç', 'Merkez', 'Süloğlu', 'Uzunköprü'],
   'Elazığ': ['Ağın', 'Alacakaya', 'Arıcak', 'Baskil', 'Karakoçan', 'Keban', 'Kovancılar', 'Maden', 'Merkez', 'Palu', 'Sivrice'],
   'Erzincan': ['Çayırlı', 'İliç', 'Kemah', 'Kemaliye', 'Merkez', 'Otlukbeli', 'Refahiye', 'Tercan', 'Üzümlü'],
   'Erzurum': ['Aşkale', 'Aziziye', 'Çat', 'Hınıs', 'Horasan', 'İspir', 'Karaçoban', 'Karayazı', 'Köprüköy', 'Narman', 'Oltu', 'Olur', 'Palandöken', 'Pasinler', 'Pazaryolu', 'Şenkaya', 'Tekman', 'Tortum', 'Uzundere', 'Yakutiye'],
   'Eskişehir': ['Alpu', 'Beylikova', 'Çifteler', 'Günyüzü', 'Han', 'İnönü', 'Mahmudiye', 'Mihalgazi', 'Mihalıççık', 'Odunpazarı', 'Sarıcakaya', 'Seyitgazi', 'Sivrihisar', 'Tepebaşı'],
   'Gaziantep': ['Araban', 'İslahiye', 'Karkamış', 'Nizip', 'Nurdağı', 'Oğuzeli', 'Şahinbey', 'Şehitkamil', 'Yavuzeli'],
   'Giresun': ['Alucra', 'Bulancak', 'Çamoluk', 'Çanakçı', 'Dereli', 'Doğankent', 'Espiye', 'Eynesil', 'Görele', 'Güce', 'Keşap', 'Merkez', 'Piraziz', 'Şebinkarahisar', 'Tirebolu', 'Yağlıdere'],
   'Gümüşhane': ['Kelkit', 'Köse', 'Kürtün', 'Merkez', 'Şiran', 'Torul'],
   'Hakkari': ['Çukurca', 'Derecik', 'Merkez', 'Şemdinli', 'Yüksekova'],
   'Hatay': ['Altınözü', 'Antakya', 'Arsuz', 'Belen', 'Defne', 'Dörtyol', 'Erzin', 'Hassa', 'İskenderun', 'Kırıkhan', 'Kumlu', 'Payas', 'Reyhanlı', 'Samandağ', 'Yayladağı'],
   'Isparta': ['Aksu', 'Atabey', 'Eğirdir', 'Gelendost', 'Gönen', 'Keçiborlu', 'Merkez', 'Senirkent', 'Sütçüler', 'Şarkikaraağaç', 'Uluborlu', 'Yalvaç', 'Yenişarbademli'],
   'Mersin': ['Akdeniz', 'Anamur', 'Aydıncık', 'Bozyazı', 'Çamlıyayla', 'Erdemli', 'Gülnar', 'Mezitli', 'Mut', 'Silifke', 'Tarsus', 'Toroslar', 'Yenişehir'],
   'İstanbul': ['Adalar', 'Arnavutköy', 'Ataşehir', 'Avcılar', 'Bağcılar', 'Bahçelievler', 'Bakırköy', 'Başakşehir', 'Bayrampaşa', 'Beşiktaş', 'Beykoz', 'Beylikdüzü', 'Beyoğlu', 'Büyükçekmece', 'Çatalca', 'Çekmeköy', 'Esenler', 'Esenyurt', 'Eyüpsultan', 'Fatih', 'Gaziosmanpaşa', 'Güngören', 'Kadıköy', 'Kağıthane', 'Kartal', 'Küçükçekmece', 'Maltepe', 'Pendik', 'Sancaktepe', 'Sarıyer', 'Silivri', 'Sultanbeyli', 'Sultangazi', 'Şile', 'Şişli', 'Tuzla', 'Ümraniye', 'Üsküdar', 'Zeytinburnu'],
   'İzmir': ['Aliağa', 'Balçova', 'Bayındır', 'Bayraklı', 'Bergama', 'Beydağ', 'Bornova', 'Buca', 'Çeşme', 'Çiğli', 'Dikili', 'Foça', 'Gaziemir', 'Güzelbahçe', 'Karabağlar', 'Karaburun', 'Karşıyaka', 'Kemalpaşa', 'Kınık', 'Kiraz', 'Konak', 'Menderes', 'Menemen', 'Narlıdere', 'Ödemiş', 'Seferihisar', 'Selçuk', 'Tire', 'Torbalı', 'Urla'],
   'Kars': ['Akyaka', 'Arpaçay', 'Digor', 'Kağızman', 'Merkez', 'Sarıkamış', 'Selim', 'Susuz'],
   'Kastamonu': ['Abana', 'Ağlı', 'Araç', 'Azdavay', 'Bozkurt', 'Cide', 'Çatalzeytin', 'Daday', 'Devrekani', 'Doğanyurt', 'Hanönü', 'İhsangazi', 'İnebolu', 'Küre', 'Merkez', 'Pınarbaşı', 'Seydiler', 'Şenpazar', 'Taşköprü', 'Tosya'],
   'Kayseri': ['Akkışla', 'Bünyan', 'Develi', 'Felahiye', 'Hacılar', 'İncesu', 'Kocasinan', 'Melikgazi', 'Özvatan', 'Pınarbaşı', 'Sarıoğlan', 'Sarız', 'Talas', 'Tomarza', 'Yahyalı', 'Yeşilhisar'],
   'Kırklareli': ['Babaeski', 'Demirköy', 'Kofçaz', 'Lüleburgaz', 'Merkez', 'Pehlivanköy', 'Pınarhisar', 'Vize'],
   'Kırşehir': ['Akçakent', 'Akpınar', 'Boztepe', 'Çiçekdağı', 'Kaman', 'Merkez', 'Mucur'],
   'Kocaeli': ['Başiskele', 'Çayırova', 'Darıca', 'Derince', 'Dilovası', 'Gebze', 'Gölcük', 'İzmit', 'Kandıra', 'Karamürsel', 'Kartepe', 'Körfez'],
   'Konya': ['Ahırlı', 'Akören', 'Akşehir', 'Altınekin', 'Beyşehir', 'Bozkır', 'Cihanbeyli', 'Çeltik', 'Çumra', 'Derbent', 'Derebucak', 'Doğanhisar', 'Emirgazi', 'Ereğli', 'Güneysınır', 'Hadim', 'Halkapınar', 'Hüyük', 'Ilgın', 'Kadınhanı', 'Karapınar', 'Karatay', 'Kulu', 'Meram', 'Sarayönü', 'Selçuklu', 'Seydişehir', 'Taşkent', 'Tuzlukçu', 'Yalıhüyük', 'Yunak'],
   'Kütahya': ['Altıntaş', 'Aslanapa', 'Çavdarhisar', 'Domaniç', 'Dumlupınar', 'Emet', 'Gediz', 'Hisarcık', 'Merkez', 'Pazarlar', 'Simav', 'Şaphane', 'Tavşanlı'],
   'Malatya': ['Akçadağ', 'Arapgir', 'Arguvan', 'Battalgazi', 'Darende', 'Doğanşehir', 'Doğanyol', 'Hekimhan', 'Kale', 'Kuluncak', 'Pütürge', 'Yazıhan', 'Yeşilyurt'],
   'Manisa': ['Ahmetli', 'Akhisar', 'Alaşehir', 'Demirci', 'Gölmarmara', 'Gördes', 'Kırkağaç', 'Köprübaşı', 'Kula', 'Salihli', 'Sarıgöl', 'Saruhanlı', 'Selendi', 'Soma', 'Şehzadeler', 'Turgutlu', 'Yunusemre'],
   'Kahramanmaraş': ['Afşin', 'Andırın', 'Çağlayancerit', 'Dulkadiroğlu', 'Ekinözü', 'Elbistan', 'Göksun', 'Nurhak', 'Onikişubat', 'Pazarcık', 'Türkoğlu'],
   'Mardin': ['Artuklu', 'Dargeçit', 'Derik', 'Kızıltepe', 'Mazıdağı', 'Midyat', 'Nusaybin', 'Ömerli', 'Savur', 'Yeşilli'],
   'Muğla': ['Bodrum', 'Dalaman', 'Datça', 'Fethiye', 'Kavaklıdere', 'Köyceğiz', 'Marmaris', 'Menteşe', 'Milas', 'Ortaca', 'Seydikemer', 'Ula', 'Yatağan'],
   'Muş': ['Bulanık', 'Hasköy', 'Korkut', 'Malazgirt', 'Merkez', 'Varto'],
   'Nevşehir': ['Acıgöl', 'Avanos', 'Derinkuyu', 'Gülşehir', 'Hacıbektaş', 'Kozaklı', 'Merkez', 'Ürgüp'],
   'Niğde': ['Altunhisar', 'Bor', 'Çamardı', 'Çiftlik', 'Merkez', 'Ulukışla'],
   'Ordu': ['Akkuş', 'Altınordu', 'Aybastı', 'Çamaş', 'Çatalpınar', 'Çaybaşı', 'Fatsa', 'Gölköy', 'Gülyalı', 'Gürgentepe', 'İkizce', 'Kabadüz', 'Kabataş', 'Korgan', 'Kumru', 'Mesudiye', 'Perşembe', 'Ulubey', 'Ünye'],
   'Rize': ['Ardeşen', 'Çamlıhemşin', 'Çayeli', 'Derepazarı', 'Fındıklı', 'Güneysu', 'Hemşin', 'İkizdere', 'İyidere', 'Kalkandere', 'Merkez', 'Pazar'],
   'Sakarya': ['Adapazarı', 'Akyazı', 'Arifiye', 'Erenler', 'Ferizli', 'Geyve', 'Hendek', 'Karapürçek', 'Karasu', 'Kaynarca', 'Kocaali', 'Pamukova', 'Sapanca', 'Serdivan', 'Söğütlü', 'Taraklı'],
   'Samsun': ['Alaçam', 'Asarcık', 'Atakum', 'Ayvacık', 'Bafra', 'Canik', 'Çarşamba', 'Havza', 'İlkadım', 'Kavak', 'Ladik', 'Ondokuzmayıs', 'Salıpazarı', 'Tekkeköy', 'Terme', 'Vezirköprü', 'Yakakent'],
   'Siirt': ['Baykan', 'Eruh', 'Kurtalan', 'Merkez', 'Pervari', 'Şirvan', 'Tillo'],
   'Sinop': ['Ayancık', 'Boyabat', 'Dikmen', 'Durağan', 'Erfelek', 'Gerze', 'Merkez', 'Saraydüzü', 'Türkeli'],
   'Sivas': ['Akıncılar', 'Altınyayla', 'Divriği', 'Doğanşar', 'Gemerek', 'Gölova', 'Gürün', 'Hafik', 'İmranlı', 'Kangal', 'Koyulhisar', 'Merkez', 'Suşehri', 'Şarkışla', 'Ulaş', 'Yıldızeli', 'Zara'],
   'Tekirdağ': ['Çerkezköy', 'Çorlu', 'Ergene', 'Hayrabolu', 'Kapaklı', 'Malkara', 'Marmaraereğlisi', 'Muratlı', 'Saray', 'Süleymanpaşa', 'Şarköy'],
   'Tokat': ['Almus', 'Artova', 'Başçiftlik', 'Erbaa', 'Merkez', 'Niksar', 'Pazar', 'Reşadiye', 'Sulusaray', 'Turhal', 'Yeşilyurt', 'Zile'],
   'Trabzon': ['Akçaabat', 'Araklı', 'Arsin', 'Beşikdüzü', 'Çarşıbaşı', 'Çaykara', 'Dernekpazarı', 'Düzköy', 'Hayrat', 'Köprübaşı', 'Maçka', 'Of', 'Ortahisar', 'Sürmene', 'Şalpazarı', 'Tonya', 'Vakfıkebir', 'Yomra'],
   'Tunceli': ['Çemişgezek', 'Hozat', 'Mazgirt', 'Merkez', 'Nazımiye', 'Ovacık', 'Pertek', 'Pülümür'],
   'Şanlıurfa': ['Akçakale', 'Birecik', 'Bozova', 'Ceylanpınar', 'Eyyübiye', 'Halfeti', 'Haliliye', 'Harran', 'Hilvan', 'Karaköprü', 'Siverek', 'Suruç', 'Viranşehir'],
   'Uşak': ['Banaz', 'Eşme', 'Karahallı', 'Merkez', 'Sivaslı', 'Ulubey'],
   'Van': ['Bahçesaray', 'Başkale', 'Çaldıran', 'Çatak', 'Edremit', 'Erciş', 'Gevaş', 'Gürpınar', 'İpekyolu', 'Muradiye', 'Özalp', 'Saray', 'Tuşba'],
   'Yozgat': ['Akdağmadeni', 'Aydıncık', 'Boğazlıyan', 'Çandır', 'Çayıralan', 'Çekerek', 'Kadışehri', 'Merkez', 'Saraykent', 'Sarıkaya', 'Sorgun', 'Şefaatli', 'Yenifakılı', 'Yerköy'],
   'Zonguldak': ['Alaplı', 'Çaycuma', 'Devrek', 'Ereğli', 'Gökçebey', 'Kilimli', 'Kozlu', 'Merkez'],
   'Aksaray': ['Ağaçören', 'Eskil', 'Gülağaç', 'Güzelyurt', 'Merkez', 'Ortaköy', 'Sarıyahşi'],
   'Bayburt': ['Aydıntepe', 'Demirözü', 'Merkez'],
   'Karaman': ['Ayrancı', 'Başyayla', 'Ermenek', 'Kazımkarabekir', 'Merkez', 'Sarıveliler'],
   'Kırıkkale': ['Bahşili', 'Balışeyh', 'Çelebi', 'Delice', 'Karakeçili', 'Keskin', 'Merkez', 'Sulakyurt', 'Yahşihan'],
   'Batman': ['Beşiri', 'Gercüş', 'Hasankeyf', 'Kozluk', 'Merkez', 'Sason'],
   'Şırnak': ['Beytüşşebap', 'Cizre', 'Güçlükonak', 'İdil', 'Merkez', 'Silopi', 'Uludere'],
   'Bartın': ['Amasra', 'Kurucaşile', 'Merkez', 'Ulus'],
   'Ardahan': ['Çıldır', 'Damal', 'Göle', 'Hanak', 'Merkez', 'Posof'],
   'Iğdır': ['Aralık', 'Karakoyunlu', 'Merkez', 'Tuzluca'],
   'Yalova': ['Altınova', 'Armutlu', 'Çınarcık', 'Çiftlikköy', 'Merkez', 'Termal'],
   'Karabük': ['Eflani', 'Eskipazar', 'Merkez', 'Ovacık', 'Safranbolu', 'Yenice'],
   'Kilis': ['Elbeyli', 'Merkez', 'Musabeyli', 'Polateli'],
   'Osmaniye': ['Bahçe', 'Düziçi', 'Hasanbeyli', 'Kadirli', 'Merkez', 'Sumbas', 'Toprakkale'],
   'Düzce': ['Akçakoca', 'Cumayeri', 'Çilimli', 'Gölyaka', 'Gümüşova', 'Kaynaşlı', 'Merkez', 'Yığılca'],
}

export const TR_POSTAL_CODES: Record<string, string> = {
   // İstanbul - All 39 districts
   'İstanbul-Adalar': '34970',
   'İstanbul-Arnavutköy': '34275',
   'İstanbul-Ataşehir': '34764',
   'İstanbul-Avcılar': '34310',
   'İstanbul-Bağcılar': '34200',
   'İstanbul-Bahçelievler': '34180',
   'İstanbul-Bakırköy': '34142',
   'İstanbul-Başakşehir': '34480',
   'İstanbul-Bayrampaşa': '34040',
   'İstanbul-Beşiktaş': '34330',
   'İstanbul-Beykoz': '34800',
   'İstanbul-Beylikdüzü': '34520',
   'İstanbul-Beyoğlu': '34420',
   'İstanbul-Büyükçekmece': '34500',
   'İstanbul-Çatalca': '34540',
   'İstanbul-Çekmeköy': '34782',
   'İstanbul-Esenler': '34220',
   'İstanbul-Esenyurt': '34510',
   'İstanbul-Eyüpsultan': '34050',
   'İstanbul-Fatih': '34080',
   'İstanbul-Gaziosmanpaşa': '34240',
   'İstanbul-Güngören': '34160',
   'İstanbul-Kadıköy': '34710',
   'İstanbul-Kağıthane': '34400',
   'İstanbul-Kartal': '34860',
   'İstanbul-Küçükçekmece': '34290',
   'İstanbul-Maltepe': '34840',
   'İstanbul-Pendik': '34890',
   'İstanbul-Sancaktepe': '34785',
   'İstanbul-Sarıyer': '34450',
   'İstanbul-Silivri': '34570',
   'İstanbul-Sultanbeyli': '34935',
   'İstanbul-Sultangazi': '34260',
   'İstanbul-Şile': '34980',
   'İstanbul-Şişli': '34360',
   'İstanbul-Tuzla': '34940',
   'İstanbul-Ümraniye': '34760',
   'İstanbul-Üsküdar': '34660',
   'İstanbul-Zeytinburnu': '34010',

   // Ankara
   'Ankara-Akyurt': '06750',
   'Ankara-Altındağ': '06030',
   'Ankara-Ayaş': '06710',
   'Ankara-Bala': '06760',
   'Ankara-Beypazarı': '06730',
   'Ankara-Çamlıdere': '06720',
   'Ankara-Çankaya': '06680',
   'Ankara-Çubuk': '06780',
   'Ankara-Elmadağ': '06790',
   'Ankara-Etimesgut': '06790',
   'Ankara-Evren': '06770',
   'Ankara-Gölbaşı': '06830',
   'Ankara-Güdül': '06725',
   'Ankara-Haymana': '06860',
   'Ankara-Kahramankazan': '06980',
   'Ankara-Kalecik': '06870',
   'Ankara-Keçiören': '06280',
   'Ankara-Kızılcahamam': '06890',
   'Ankara-Mamak': '06620',
   'Ankara-Nallıhan': '06900',
   'Ankara-Polatlı': '06900',
   'Ankara-Pursaklar': '06145',
   'Ankara-Sincan': '06930',
   'Ankara-Şereflikoçhisar': '06950',
   'Ankara-Yenimahalle': '06370',

   // İzmir
   'İzmir-Aliağa': '35800',
   'İzmir-Balçova': '35330',
   'İzmir-Bayındır': '35780',
   'İzmir-Bayraklı': '35510',
   'İzmir-Bergama': '35700',
   'İzmir-Beydağ': '35760',
   'İzmir-Bornova': '35040',
   'İzmir-Buca': '35390',
   'İzmir-Çeşme': '35930',
   'İzmir-Çiğli': '35580',
   'İzmir-Dikili': '35900',
   'İzmir-Foça': '35680',
   'İzmir-Gaziemir': '35410',
   'İzmir-Güzelbahçe': '35310',
   'İzmir-Karabağlar': '35150',
   'İzmir-Karaburun': '35960',
   'İzmir-Karşıyaka': '35550',
   'İzmir-Kemalpaşa': '35730',
   'İzmir-Kınık': '35740',
   'İzmir-Kiraz': '35820',
   'İzmir-Konak': '35250',
   'İzmir-Menderes': '35470',
   'İzmir-Menemen': '35660',
   'İzmir-Narlıdere': '35320',
   'İzmir-Ödemiş': '35750',
   'İzmir-Seferihisar': '35460',
   'İzmir-Selçuk': '35920',
   'İzmir-Tire': '35900',
   'İzmir-Torbalı': '35860',
   'İzmir-Urla': '35430',

   // Antalya
   'Antalya-Akseki': '07630',
   'Antalya-Aksu': '07112',
   'Antalya-Alanya': '07400',
   'Antalya-Demre': '07570',
   'Antalya-Döşemealtı': '07190',
   'Antalya-Elmalı': '07700',
   'Antalya-Finike': '07680',
   'Antalya-Gazipaşa': '07900',
   'Antalya-Gündoğmuş': '07650',
   'Antalya-İbradı': '07640',
   'Antalya-Kaş': '07580',
   'Antalya-Kemer': '07980',
   'Antalya-Kepez': '07060',
   'Antalya-Konyaaltı': '07070',
   'Antalya-Korkuteli': '07800',
   'Antalya-Kumluca': '07350',
   'Antalya-Manavgat': '07600',
   'Antalya-Muratpaşa': '07010',
   'Antalya-Serik': '07500',

   // Bursa
   'Bursa-Büyükorhan': '16870',
   'Bursa-Gemlik': '16600',
   'Bursa-Gürsu': '16580',
   'Bursa-Harmancık': '16750',
   'Bursa-İnegöl': '16400',
   'Bursa-İznik': '16860',
   'Bursa-Karacabey': '16700',
   'Bursa-Keles': '16780',
   'Bursa-Kestel': '16450',
   'Bursa-Mudanya': '16940',
   'Bursa-Mustafakemalpaşa': '16500',
   'Bursa-Nilüfer': '16110',
   'Bursa-Orhaneli': '16800',
   'Bursa-Orhangazi': '16880',
   'Bursa-Osmangazi': '16010',
   'Bursa-Yenişehir': '16900',
   'Bursa-Yıldırım': '16270',

   // Other cities - Merkez / main district
   'Adana-Seyhan': '01120',
   'Adana-Çukurova': '01330',
   'Adana-Yüreğir': '01220',
   'Adana-Sarıçam': '01321',
   'Adıyaman-Merkez': '02040',
   'Afyonkarahisar-Merkez': '03030',
   'Ağrı-Merkez': '04100',
   'Amasya-Merkez': '05100',
   'Artvin-Merkez': '08100',
   'Aydın-Efeler': '09100',
   'Balıkesir-Karesi': '10100',
   'Bilecik-Merkez': '11100',
   'Bingöl-Merkez': '12100',
   'Bitlis-Merkez': '13100',
   'Bolu-Merkez': '14100',
   'Burdur-Merkez': '15100',
   'Çanakkale-Merkez': '17100',
   'Çankırı-Merkez': '18100',
   'Çorum-Merkez': '19100',
   'Denizli-Merkezefendi': '20100',
   'Diyarbakır-Bağlar': '21100',
   'Diyarbakır-Sur': '21200',
   'Edirne-Merkez': '22100',
   'Elazığ-Merkez': '23100',
   'Erzincan-Merkez': '24100',
   'Erzurum-Yakutiye': '25100',
   'Eskişehir-Odunpazarı': '26010',
   'Eskişehir-Tepebaşı': '26120',
   'Gaziantep-Şahinbey': '27010',
   'Gaziantep-Şehitkamil': '27090',
   'Giresun-Merkez': '28100',
   'Gümüşhane-Merkez': '29100',
   'Hakkari-Merkez': '30100',
   'Hatay-Antakya': '31060',
   'Isparta-Merkez': '32100',
   'Mersin-Yenişehir': '33130',
   'Mersin-Akdeniz': '33050',
   'Mersin-Toroslar': '33220',
   'Mersin-Mezitli': '33340',
   'Kars-Merkez': '36100',
   'Kastamonu-Merkez': '37100',
   'Kayseri-Melikgazi': '38010',
   'Kayseri-Kocasinan': '38090',
   'Kırklareli-Merkez': '39100',
   'Kırşehir-Merkez': '40100',
   'Kocaeli-İzmit': '41100',
   'Kocaeli-Gebze': '41400',
   'Konya-Selçuklu': '42130',
   'Konya-Karatay': '42020',
   'Konya-Meram': '42090',
   'Kütahya-Merkez': '43100',
   'Malatya-Battalgazi': '44100',
   'Malatya-Yeşilyurt': '44090',
   'Manisa-Şehzadeler': '45020',
   'Manisa-Yunusemre': '45030',
   'Kahramanmaraş-Onikişubat': '46060',
   'Kahramanmaraş-Dulkadiroğlu': '46100',
   'Mardin-Artuklu': '47100',
   'Muğla-Menteşe': '48000',
   'Muğla-Bodrum': '48400',
   'Muğla-Fethiye': '48300',
   'Muğla-Marmaris': '48700',
   'Muş-Merkez': '49100',
   'Nevşehir-Merkez': '50100',
   'Niğde-Merkez': '51100',
   'Ordu-Altınordu': '52100',
   'Rize-Merkez': '53100',
   'Sakarya-Adapazarı': '54100',
   'Samsun-İlkadım': '55020',
   'Samsun-Atakum': '55200',
   'Siirt-Merkez': '56100',
   'Sinop-Merkez': '57100',
   'Sivas-Merkez': '58100',
   'Tekirdağ-Süleymanpaşa': '59100',
   'Tekirdağ-Çorlu': '59850',
   'Tokat-Merkez': '60100',
   'Trabzon-Ortahisar': '61100',
   'Tunceli-Merkez': '62100',
   'Şanlıurfa-Eyyübiye': '63100',
   'Şanlıurfa-Haliliye': '63300',
   'Uşak-Merkez': '64100',
   'Van-İpekyolu': '65100',
   'Van-Tuşba': '65300',
   'Yozgat-Merkez': '66100',
   'Zonguldak-Merkez': '67100',
   'Aksaray-Merkez': '68100',
   'Bayburt-Merkez': '69100',
   'Karaman-Merkez': '70100',
   'Kırıkkale-Merkez': '71100',
   'Batman-Merkez': '72100',
   'Şırnak-Merkez': '73100',
   'Bartın-Merkez': '74100',
   'Ardahan-Merkez': '75100',
   'Iğdır-Merkez': '76100',
   'Yalova-Merkez': '77100',
   'Karabük-Merkez': '78100',
   'Kilis-Merkez': '79100',
   'Osmaniye-Merkez': '80100',
   'Düzce-Merkez': '81100',
}

/** Get postal code for a city-district pair */
export function getPostalCode(city: string, district: string): string {
   return TR_POSTAL_CODES[`${city}-${district}`] || ''
}

/** Get districts for a given city */
export function getDistricts(city: string): string[] {
   return TR_DISTRICTS[city] || []
}
